version: 0.16.2.{build}
os: Visual Studio 2015

cache:
  - urlpicker\src\packages -> urlpicker\src\**\packages.config          # preserve "packages" directory but will reset it if packages.config is modified
  - urlpicker\node_modules                                # local npm modules
  - '%APPDATA%\npm-cache'                                 # npm cache
  - '%APPDATA%\npm'                                       # npm global

configuration: Release

environment:
  version_suffix: 

branches:
  only:
    - develop
    - master

install:
  - ps: .\appveyor\appveyor-semver.ps1
  - ps: Update-AppveyorBuild -Version $Env:appveyor_version
  - cmd: npm install -g grunt
  - cmd: nuget update -Self
  - cmd: node --version
  - cmd: npm --version
  - cmd: appveyor\appveyor-package-version-patch.cmd

assembly_info:
  patch: true
  file: 'urlpicker\src\**\AssemblyInfo.*'
  assembly_version: '$(appveyor_build_version)'
  assembly_file_version: '$(appveyor_build_version)'
  assembly_informational_version: '$(mssemver)'

build_script:
- cmd: >-
    cd urlpicker

    npm install

    grunt umbraco

    grunt nuget

    appveyor PushArtifact "pkg/UrlPicker_%mssemver%.zip" -Type Zip

    appveyor PushArtifact "pkg/UrlPicker.%mssemver%.nupkg" -Type NuGetPackage

deploy:
      # Umbraco MyGet community feed
  - provider: NuGet
    server: https://www.myget.org/F/umbraco-packages/api/v2/package
    symbol_server: https://nuget.symbolsource.org/MyGet/umbraco-packages
    api_key:
      secure: SASQGWG/4zNns7bwSSsJ5RPvKcKfJsBeEPuw69wsVPA3PO739QmzVtc5VwQwgvbr
    artifact: /.*\.nupkg/
    on:
      branch: develop